### ISSUE TITLE
Feature Request: Procedural tile generation / route viability

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#1]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I want procedural tile generation in a crossroad game to ensure endless and unpredictable road layouts for a constantly engaging experience."

### Description:
_Describe the feature you'd like to see added._

- This issue addresses the need to manage a series of tile generators in such a way they generate either a "free" or "blocked" tile, ensuring there is always a free route from the top of the screen to the bottom.
If an algorithmic approach to this is not effective then a template based approach to level generation will be explored.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #12
