### ISSUE TITLE
Feature Request: Score

### ISSUE THREAD

**Issue by LiamMcKenzie** [LiamMcKenzie/ScaredKrow#17]
### Use Case:
_Outline the use case and/or provide a user story._
- This will be the primary goal of the game

### Description:
_Describe the feature you'd like to see added._
- Number in top right that increases based on distance travelled. (Similar to crossy road)
- Text from game design document: "High score via distance travelled (+ pickups?) "
- Here is a mockup image provided to us from the design team:
![image](https://github.com/LiamMcKenzie/ScaredKrow/assets/90590068/2398127d-bc25-4a2f-8959-a06eaf07f03c)

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #19
