### ISSUE TITLE
Feature Request: Crow enemy

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#2]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I want a crow enemy in the game to add a challenging aerial threat, enhancing the gameplay experience and encouraging strategic planning and movement"

### Description:
_Describe the feature you'd like to see added._
- This issue involves plotting the movement and collision of the crow enemy.

**Comment by DevonHenderson** [comment]
### From the Design document:

 - Flies over the screen from the top to bottom
 - The effect area is 3x3 tiles
 - Warning UI before they swoop, with visual and audio cues
 - If the player is in the crow’s shadow (3x3 tile) and not hiding, the crow will hit the player and they will lose all items/power ups (shields)
 - The crows gain one random equipped powerup for a short period of time from hitting the player
 - The player can either hide in a hay bale or avoid the crow

**For the purpose of this issue I will only initially cover the crow movement, collision area and a warning UI when the crow spawns**

**Comment by DevonHenderson** [comment]
Closing issue as the basic crow spawning, movement and shadow detection resolved in pull request:
 - #14
