### ISSUE TITLE
Feature Request: Title Screen

### ISSUE THREAD

**Issue by LiamMcKenzie** [LiamMcKenzie/ScaredKrow#25]
### Use Case:
_Outline the use case and/or provide a user story._
- The users will want to know what the controls are and what the game is called before playing.
- Currently after each death the game stays on the game over screen. its important that the players first impressions are of the title screen and not the game over screen.

### Description:
_Describe the feature you'd like to see added._
- We have a title screen mock up from the design team. When the game starts and after each death the player should be sent here.

![image (2)](https://github.com/LiamMcKenzie/ScaredKrow/assets/90590068/fc67cbe6-9183-4457-868e-986cac6d3f9c)

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #28
