### ISSUE TITLE
Feature Request: Player movement

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#3]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I need movement to navigate through tile based levels, giving me a sense of agency and enhancing immersion."

### Description:
_Describe the feature you'd like to see added._
- This issue addresses the need for basic four directional movement on a tile based grid.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #11 
 - #20
