### ISSUE TITLE
Feature request: Camera movement

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#4]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player I require camera movement to encourage me to navigate up the course so that the gameplay has a sense of urgency."

### Description:
_Describe the feature you'd like to see added._
- This issue addresses the need for camera movement along the y-axis of the tile map.
- This should have a variable for speed so we can later increase this to increase difficulty.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #12 
 - #15
