### ISSUE TITLE
Feature Request: Clothing Pickups

### ISSUE THREAD

**Issue by LiamMcKenzie** [LiamMcKenzie/ScaredKrow#5]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I would like to pickup clothing items to provide my character with extra hits so that I have a reason to further strategise my movement and take risks in regard to level traversal."

### Description:
_Describe the feature you'd like to see added._
- This feature involves the player collecting the clothing pickups. There are three articles of clothing and the player can only have one of each equipped, so some thought needs to go into the drop rate of each item. E.g., if the player is wearing pants but not a hat, should the drop rate of pants be reduced?
- This issue is linked to #8 and will likely have some shared scripting.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #40 
 - #47
