### ISSUE TITLE
Feature Request: Clothing displayed on player

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#8]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I want to see my character's clothing pickups displayed on the character, so that I can gauge how vulnerable my character is."

### Description:
_Describe the feature you'd like to see added._
- This issue involves managing the player appearance to reflect the current clothing items they have in their position. This issue is linked to #5 and will likely have some shared scripting.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #47
