### ISSUE TITLE
Feature Request: Hit points

### ISSUE THREAD

**Issue by JohnathanGlasgow** [LiamMcKenzie/ScaredKrow#9]
### Use Case:
_Outline the use case and/or provide a user story._
- "As a player, I want to have a finite number of hit points, so that I will have of sense of consequence for gameplay mistakes."

### Description:
_Describe the feature you'd like to see added._
- This issue involves managing the player and game state so that a game over condition is reached when the player is at zero hit points.
- The player can effectively take a maximum of 4 hits- one for each article of clothing, and a final hit in the "naked" state.

**Comment by DevonHenderson** [comment]
Closing issue as resolved in:
 - #33 
 - #43 
 - #47
